### ISSUE TITLE
Add Dart to the set of programming languages

### ISSUE THREAD

**Issue by flelli** [RockyLelli/PlayGround1#16]
[Dart](https://dart.dev/) is used in Flutter.

**Comment by flelli** [comment]
@dbbd59 can help with this :)

**Comment by dbbd59** [comment]
Hi! this can be the starting point:
https://dart.dev/tutorials

![giphy](https://user-images.githubusercontent.com/16138584/188873212-0666a9bd-4580-4d91-bf26-2ba5590e5260.gif)
